In [3]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

/Users/Cyrob/anaconda2/envs/sreg_venv/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
# define documents
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']
# define class labels
labels = np.array([1,1,1,1,1,0,0,0,0,0])


In [8]:
vocab_size = 50
encoded_docs = [keras.preprocessing.text.one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[29, 27], [15, 4], [39, 43], [29, 4], [23], [34], [9, 43], [38, 15], [9, 4], [8, 18, 27, 9]]


In [10]:
# pad documents to a max length of 4 words
max_length = 4
padded_docs = keras.preprocessing.sequence.pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[29 27  0  0]
 [15  4  0  0]
 [39 43  0  0]
 [29  4  0  0]
 [23  0  0  0]
 [34  0  0  0]
 [ 9 43  0  0]
 [38 15  0  0]
 [ 9  4  0  0]
 [ 8 18 27  9]]


In [12]:
# define the model
model = keras.models.Sequential()
model.add(keras.layers.Embedding(vocab_size, 8, input_length=max_length))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
# summarize the model
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 4, 8)              400       
_________________________________________________________________
flatten (Flatten)            (None, 32)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None
